jobs:
  main:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./test/ci

name: Action

on:
  schedule:
    - cron: "0 */6 * * *"
